9
['exec.py', 'null', 'on', 'null', 'null', 'null', 'grid', '0', '0']
Process Process-1:
Traceback (most recent call last):
  File "/home/chiara/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/chiara/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chiara/Desktop/wildfly-18.0.1.Final/bin/online.py", line 100, in run_online
    main(params)
  File "/home/chiara/Desktop/wildfly-18.0.1.Final/bin/online.py", line 302, in main
    tildeload = tildeload_df[load_index_list].sum(axis=1).clip(lower=0).values.tolist()
  File "/home/chiara/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2986, in __getitem__
    indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
  File "/home/chiara/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1285, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/chiara/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/chiara/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1185, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: '[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] not in index'
Finito!
